version: '3'
services: 
  redis:
    image: 'redis:latest'
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    expose:
      - "5000"
  apirest:
    build:
      dockerfile: Dockerfile
      context: ./calc2
    volumes: 
      - ./calc2/api:/app/api
      - ./calc2/package.json:/app/package.json
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_HOST=worker
      - WORKER_PORT=5000
      - TOKEN_SECRET=asdfljsdfoi3429023
    depends_on: 
      - worker
    #ports: 
    #  - "3001:3001"
  site:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ./calc1
    volumes: 
      - ./calc1/public:/app/public
      - ./calc1/src:/app/src
      - ./calc1/views:/app/views
      - ./calc1/package.json:/app/package.json
    #ports: 
    #  - "80:3000"
  nginx:
    depends_on: 
      - site
      - apirest
      - worker
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
  